<a href="https://colab.research.google.com/github/Kirtan-Chitalia/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#00. pytorch Fundamentals

In [ ]:
import torch
print(torch.__version__)

2.9.0+cu126


### **Intro to Tensors**


creating tensors

In [ ]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as Python int
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX2  = torch.tensor([[[
    [1,2,3],
    [3,6,9],
    [2,4,5]
]]])

MATRIX2

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])

In [ ]:
MATRIX2.ndim

4

In [ ]:
MATRIX2.shape

torch.Size([1, 1, 3, 3])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

  why random tensors ?
- Random tensors are important because the way many neural network learn is that
  they start with full of random numbers and then adjust those random numbers
  to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...`

In [ ]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0953, 0.5406, 0.3440, 0.4561],
        [0.4096, 0.0896, 0.1508, 0.1676],
        [0.8639, 0.3161, 0.0297, 0.7617]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### zeros and ones

In [ ]:
#creating a tensor of all zeros
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones*random_tensor

tensor([[0.0953, 0.5406, 0.3440, 0.4561],
        [0.4096, 0.0896, 0.1508, 0.1676],
        [0.8639, 0.3161, 0.0297, 0.7617]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
#creating a tensor with 100 zeros
zero_100 = torch.zeros(10,10)
zero_100

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### create a range of tensors and tensor-like

In [ ]:
# use torch.arange()
one_to_ten=torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.arange(start=0,end=1000,step=66)

tensor([  0,  66, 132, 198, 264, 330, 396, 462, 528, 594, 660, 726, 792, 858,
        924, 990])

In [ ]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor datatype

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor


tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor


tensor([ 9., 36., 81.])

### Getting information from tensors

1. `shape` - what shape is the tensor? (some operations require specific shape rules)

2. `dtype` - what datatype are the elements within the tensor stored in?

3. `device` - what device is the tensor stored on? (usually GPU or CPU)

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2349, 0.6412, 0.9779, 0.3320],
        [0.1087, 0.4142, 0.1908, 0.6136],
        [0.0673, 0.8648, 0.2314, 0.6856]])

In [ ]:
print(some_tensor)
print(f"Datatype of the tensor: {some_tensor.dtype}")
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Device of the tensor: {some_tensor.device}")

tensor([[0.2349, 0.6412, 0.9779, 0.3320],
        [0.1087, 0.4142, 0.1908, 0.6136],
        [0.0673, 0.8648, 0.2314, 0.6856]])
Datatype of the tensor: torch.float32
Shape of the tensor: torch.Size([3, 4])
Device of the tensor: cpu


### Manipulating tensors

tensor operations include :
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
#Addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiplication
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtraction
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# PyTorch functions
torch.mul(tensor,10) , torch.add(tensor,10)

(tensor([10, 20, 30]), tensor([11, 12, 13]))

Matrix Multiplication

In [ ]:
print(tensor, "*", tensor)
print(f"equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals: tensor([1, 4, 9])


In [ ]:
# Dot Product
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value+= tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 732 µs, sys: 0 ns, total: 732 µs
Wall time: 802 µs


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 208 µs, sys: 0 ns, total: 208 µs
Wall time: 610 µs


tensor(14)

higher dimensions

In [ ]:
# torch.matmul(torch.rand(3,2),torch.rand(3,2)) ## error

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.4194, 0.1704, 0.9188],
        [0.4512, 0.2072, 1.0521],
        [0.5089, 0.1533, 0.9729]])

In [ ]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.6737, 0.1241],
        [1.0920, 0.5664]])

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
#to fix we have to transpose
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (aggregation)

In [ ]:
x = torch.arange(1,101,10)
x , x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
torch.min(x) , x.min()

(tensor(1), tensor(1))

In [ ]:
torch.max(x) , x.max()

(tensor(91), tensor(91))

In [ ]:
# torch.mean() function requires float32 dtype
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

Positional min/max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# find the position in the tensor that has the minimun value with argmin() -> returns index value
x.argmin()

tensor(0)

In [ ]:
# find the position in the tensor that has the maximun value with argmax() -> returns index value
x.argmax()

tensor(9)

## reshaping , stacking , squeezing and unsqueezing tensors

In [ ]:
# Creating a tensor
import torch
x = torch.arange(1.,10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

Reshaping - reshapes an input tensor to a defined shape
           ,Add an extra dimension


In [ ]:
x_reshaped = x.reshape(1,9)
x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

View - Returns a view of the original tensor in a different shape but shares the same data as the original tensor.

In [ ]:
z = x.view(1,9)
z , z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

Stack - Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim =0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

Squeeze - Squeezes input to remove all the dimenions with value 1

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


Unsqueeze - Returns input with a dimension value of 1 added at dim.

In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


Permute - Returns a view of the original input with its dimensions permuted (rearranged) to dims

In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0] = 728218
x_original[0,0,0] , x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

# Indexing (Selecting data from tensors)

Indexing with Pythorch is Similar to Indexing in Numpy

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on our middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's index on our most inner bracket (dim=2)
x[0][0][0]

tensor(1)

In [ ]:
# how to get number 9
x[0][2][2]

tensor(9)

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [ ]:
# how to get 3,6,9
x[:, :, 2]

tensor([[3, 6, 9]])

# PyTorch tensors & NumPy

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.  

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:
* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - NumPy array -> PyTorch tensor.
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - PyTorch tensor -> NumPy array.


In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
# Change the value of the array
array = array + 1
array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor
tensor = tensor + 1
tensor , numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take the random out of random)

As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.

How does this relate to neural networks and deep learning then?

We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

In short:

``start with random numbers -> tensor operations -> try to make better (again and again and again)``

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.


In [ ]:
import torch

random_A = torch.rand(3,4)
random_B = torch.rand(3,4)

print(random_A)
print(random_B)
print(random_A == random_B)

tensor([[0.6282, 0.9537, 0.7157, 0.0735],
        [0.6143, 0.3396, 0.3141, 0.0357],
        [0.9576, 0.4784, 0.2380, 0.3471]])
tensor([[0.6231, 0.3872, 0.8750, 0.4907],
        [0.5567, 0.6324, 0.9897, 0.0774],
        [0.6374, 0.0448, 0.7675, 0.2310]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Lets make random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_D = torch.rand(3,4)

print(random_C)
print(random_D)
print(random_C == random_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors on GPUs (and making faster computations)

In [ ]:
!nvidia-smi

Sat Jan 31 09:36:20 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   50C    P8             12W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
# Check for GPU access on PYTORCH
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

Putting tensors and models on GPU


In [ ]:
# create a tensor
tensor = torch.tensor([1,2,3])

#tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor on GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
#moving tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])